var searchData=
[
  ['detection_20entry_20point_20a_20href_20file_3a_20home_20ashoumar_20androidstudioprojects_20androidstorage_20app_20src_20main_20cpp_20docs_20html_20root_5f_5fchecker_5f8cpp_20html_20tt_20root_5fchecker_20cpp_20tt_20a_0',['Root Detection Entry Point - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/root__checker_8cpp.html&quot; &gt;&lt;tt&gt;root_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md3',1,'']]],
  ['detection_20system_20a_20href_20file_3a_20home_20ashoumar_20androidstudioprojects_20androidstorage_20app_20src_20main_20cpp_20docs_20html_20native_5f_5femulator_5f_5fchecker_5f8cpp_20html_20tt_20native_5femulator_5fchecker_20cpp_20tt_20a_1',['Emulator Detection System - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/native__emulator__checker_8cpp.html&quot; &gt;&lt;tt&gt;native_emulator_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md6',1,'']]],
  ['detection_20system_20a_20href_20file_3a_20home_20ashoumar_20androidstudioprojects_20androidstorage_20app_20src_20main_20cpp_20docs_20html_20native_5f_5froot_5f_5fchecker_5f8cpp_20html_20tt_20native_5froot_5fchecker_20cpp_20tt_20a_2',['Root Detection System - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/native__root__checker_8cpp.html&quot; &gt;&lt;tt&gt;native_root_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md4',1,'']]],
  ['dobusyboxbinariesexist_3',['doBusyBoxBinariesExist',['../native__root__checker_8cpp.html#a060dccfced5eafb7b532f188e440f0ac',1,'native_root_checker.cpp']]],
  ['docs_20html_20native_5f_5femulator_5f_5fchecker_5f8cpp_20html_20tt_20native_5femulator_5fchecker_20cpp_20tt_20a_4',['Emulator Detection System - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/native__emulator__checker_8cpp.html&quot; &gt;&lt;tt&gt;native_emulator_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md6',1,'']]],
  ['docs_20html_20native_5f_5froot_5f_5fchecker_5f8cpp_20html_20tt_20native_5froot_5fchecker_20cpp_20tt_20a_5',['Root Detection System - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/native__root__checker_8cpp.html&quot; &gt;&lt;tt&gt;native_root_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md4',1,'']]],
  ['docs_20html_20native_5f_5fsystem_5f_5fintegrity_5f_5fverifier_5f8cpp_20html_20tt_20native_5fsystem_5fintegrity_5fverifier_20cpp_20tt_20a_6',['System Integrity Checker - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/native__system__integrity__verifier_8cpp.html&quot; &gt;&lt;tt&gt;native_system_integrity_verifier.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md5',1,'']]],
  ['docs_20html_20root_5f_5fchecker_5f8cpp_20html_20tt_20root_5fchecker_20cpp_20tt_20a_7',['Root Detection Entry Point - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/root__checker_8cpp.html&quot; &gt;&lt;tt&gt;root_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md3',1,'']]],
  ['dosuperuserappsexist_8',['doSuperUserAppsExist',['../native__root__checker_8cpp.html#a3cce26ee629326e61652083aa2b94452',1,'native_root_checker.cpp']]],
  ['dosuperuserbinariesexist_9',['doSuperUserBinariesExist',['../native__root__checker_8cpp.html#a709534c371b79996a1bfe3f0e83311da',1,'native_root_checker.cpp']]],
  ['dowritablesystempartitionsexist_10',['doWritableSystemPartitionsExist',['../native__system__integrity__verifier_8cpp.html#a612fbfc26b7234e21dd5205929bc23c5',1,'native_system_integrity_verifier.cpp']]]
];
