var searchData=
[
  ['a_20href_20file_3a_20home_20ashoumar_20androidstudioprojects_20androidstorage_20app_20src_20main_20cpp_20docs_20html_20root_5f_5fchecker_5f8cpp_20html_20tt_20root_5fchecker_20cpp_20tt_20a_0',['Root Detection Entry Point - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/root__checker_8cpp.html&quot; &gt;&lt;tt&gt;root_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md2',1,'']]],
  ['a_20privacy_20focused_20photo_20management_20solution_1',['VaultPic: A Privacy-Focused Photo Management Solution',['../index.html',1,'']]],
  ['androidstorage_20app_20src_20main_20cpp_20docs_20html_20root_5f_5fchecker_5f8cpp_20html_20tt_20root_5fchecker_20cpp_20tt_20a_2',['Root Detection Entry Point - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/root__checker_8cpp.html&quot; &gt;&lt;tt&gt;root_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md2',1,'']]],
  ['androidstudioprojects_20androidstorage_20app_20src_20main_20cpp_20docs_20html_20root_5f_5fchecker_5f8cpp_20html_20tt_20root_5fchecker_20cpp_20tt_20a_3',['Root Detection Entry Point - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/root__checker_8cpp.html&quot; &gt;&lt;tt&gt;root_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md2',1,'']]],
  ['app_20src_20main_20cpp_20docs_20html_20root_5f_5fchecker_5f8cpp_20html_20tt_20root_5fchecker_20cpp_20tt_20a_4',['Root Detection Entry Point - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/root__checker_8cpp.html&quot; &gt;&lt;tt&gt;root_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md2',1,'']]],
  ['ashoumar_20androidstudioprojects_20androidstorage_20app_20src_20main_20cpp_20docs_20html_20root_5f_5fchecker_5f8cpp_20html_20tt_20root_5fchecker_20cpp_20tt_20a_5',['Root Detection Entry Point - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/root__checker_8cpp.html&quot; &gt;&lt;tt&gt;root_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md2',1,'']]]
];
