var searchData=
[
  ['home_20ashoumar_20androidstudioprojects_20androidstorage_20app_20src_20main_20cpp_20docs_20html_20native_5f_5femulator_5f_5fchecker_5f8cpp_20html_20tt_20native_5femulator_5fchecker_20cpp_20tt_20a_0',['Emulator Detection System - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/native__emulator__checker_8cpp.html&quot; &gt;&lt;tt&gt;native_emulator_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md6',1,'']]],
  ['home_20ashoumar_20androidstudioprojects_20androidstorage_20app_20src_20main_20cpp_20docs_20html_20native_5f_5froot_5f_5fchecker_5f8cpp_20html_20tt_20native_5froot_5fchecker_20cpp_20tt_20a_1',['Root Detection System - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/native__root__checker_8cpp.html&quot; &gt;&lt;tt&gt;native_root_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md4',1,'']]],
  ['home_20ashoumar_20androidstudioprojects_20androidstorage_20app_20src_20main_20cpp_20docs_20html_20native_5f_5fsystem_5f_5fintegrity_5f_5fverifier_5f8cpp_20html_20tt_20native_5fsystem_5fintegrity_5fverifier_20cpp_20tt_20a_2',['System Integrity Checker - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/native__system__integrity__verifier_8cpp.html&quot; &gt;&lt;tt&gt;native_system_integrity_verifier.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md5',1,'']]],
  ['home_20ashoumar_20androidstudioprojects_20androidstorage_20app_20src_20main_20cpp_20docs_20html_20root_5f_5fchecker_5f8cpp_20html_20tt_20root_5fchecker_20cpp_20tt_20a_3',['Root Detection Entry Point - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/root__checker_8cpp.html&quot; &gt;&lt;tt&gt;root_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md3',1,'']]],
  ['href_20file_3a_20home_20ashoumar_20androidstudioprojects_20androidstorage_20app_20src_20main_20cpp_20docs_20html_20native_5f_5femulator_5f_5fchecker_5f8cpp_20html_20tt_20native_5femulator_5fchecker_20cpp_20tt_20a_4',['Emulator Detection System - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/native__emulator__checker_8cpp.html&quot; &gt;&lt;tt&gt;native_emulator_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md6',1,'']]],
  ['href_20file_3a_20home_20ashoumar_20androidstudioprojects_20androidstorage_20app_20src_20main_20cpp_20docs_20html_20native_5f_5froot_5f_5fchecker_5f8cpp_20html_20tt_20native_5froot_5fchecker_20cpp_20tt_20a_5',['Root Detection System - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/native__root__checker_8cpp.html&quot; &gt;&lt;tt&gt;native_root_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md4',1,'']]],
  ['href_20file_3a_20home_20ashoumar_20androidstudioprojects_20androidstorage_20app_20src_20main_20cpp_20docs_20html_20native_5f_5fsystem_5f_5fintegrity_5f_5fverifier_5f8cpp_20html_20tt_20native_5fsystem_5fintegrity_5fverifier_20cpp_20tt_20a_6',['System Integrity Checker - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/native__system__integrity__verifier_8cpp.html&quot; &gt;&lt;tt&gt;native_system_integrity_verifier.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md5',1,'']]],
  ['href_20file_3a_20home_20ashoumar_20androidstudioprojects_20androidstorage_20app_20src_20main_20cpp_20docs_20html_20root_5f_5fchecker_5f8cpp_20html_20tt_20root_5fchecker_20cpp_20tt_20a_7',['Root Detection Entry Point - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/root__checker_8cpp.html&quot; &gt;&lt;tt&gt;root_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md3',1,'']]],
  ['href_20https_3a_20github_20com_20shoumarali_20androidstorage_20view_20on_20github_20→_20a_8',['&lt;a href=&quot;https://github.com/shoumarali/AndroidStorage&quot; &gt;View on GitHub →&lt;/a&gt;',['../index.html#autotoc_md1',1,'']]],
  ['html_20native_5f_5femulator_5f_5fchecker_5f8cpp_20html_20tt_20native_5femulator_5fchecker_20cpp_20tt_20a_9',['Emulator Detection System - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/native__emulator__checker_8cpp.html&quot; &gt;&lt;tt&gt;native_emulator_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md6',1,'']]],
  ['html_20native_5f_5froot_5f_5fchecker_5f8cpp_20html_20tt_20native_5froot_5fchecker_20cpp_20tt_20a_10',['Root Detection System - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/native__root__checker_8cpp.html&quot; &gt;&lt;tt&gt;native_root_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md4',1,'']]],
  ['html_20native_5f_5fsystem_5f_5fintegrity_5f_5fverifier_5f8cpp_20html_20tt_20native_5fsystem_5fintegrity_5fverifier_20cpp_20tt_20a_11',['System Integrity Checker - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/native__system__integrity__verifier_8cpp.html&quot; &gt;&lt;tt&gt;native_system_integrity_verifier.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md5',1,'']]],
  ['html_20root_5f_5fchecker_5f8cpp_20html_20tt_20root_5fchecker_20cpp_20tt_20a_12',['Root Detection Entry Point - &lt;a href=&quot;file:///home/ashoumar/AndroidStudioProjects/AndroidStorage/app/src/main/cpp/docs/html/root__checker_8cpp.html&quot; &gt;&lt;tt&gt;root_checker.cpp&lt;/tt&gt;&lt;/a&gt;',['../index.html#autotoc_md3',1,'']]],
  ['https_3a_20github_20com_20shoumarali_20androidstorage_20view_20on_20github_20→_20a_13',['&lt;a href=&quot;https://github.com/shoumarali/AndroidStorage&quot; &gt;View on GitHub →&lt;/a&gt;',['../index.html#autotoc_md1',1,'']]]
];
