name: Build and Deploy Docs
on:
  push:
    branches: [ main ]
    paths:
      - 'app/src/main/cpp/**'
      - '.github/workflows/docs.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Doxygen
        run: sudo apt-get install doxygen graphviz

      - name: Get Doxygen-Awesome
        run: |
          git clone https://github.com/jothepro/doxygen-awesome-css.git \
            app/src/main/cpp/doxygen-awesome-css

      - name: Generate Docs
        working-directory: ./app/src/main/cpp
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/src/main/cpp/docs/html
          keep_files: false